name: Support 💁‍♂️
description: Raise a support ticket
title: "[Support]: Describe your issue / support requirement here"
labels: [support]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out!
  - type: input
    attributes:
      label: Support ticket information
      description: Please elaborate on your support requirement.
      placeholder: I would like to see...
    validations:
      required: true
