name: Release

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  release:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13
      - name: "Install dependencies"
        run: "pip install -r requirements/dev-requirements.txt"
      - name: "Publish to PyPI"
        run: "./scripts/release.sh"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
